feat: whiteboard action buttons
RocketChat/Apps.Whiteboard pull request #14
Opened 2023-07-23 20:02 UTC by CulturalProfessor

Fixes(#13 ) v1

2023-07-23 20:16 UTC, CulturalProfessor commented
![image](https://github.com/RocketChat/Apps.Whiteboard/assets/92238941/f7bc230d-ac9c-45a7-980a-0606a954fd71)

2023-07-24 09:13 UTC, shiqimei requested changes

2023-07-24 09:13 UTC, shiqimei commented on whiteboard/i18n/en.json
> +    "create_whiteboard":"▢ Whiteboard"
use the value "Create Whiteboard"

2023-07-24 09:13 UTC, shiqimei commented on whiteboard/handlers/ExecuteActionButtonHandler.ts
> +                    console.log("BUTTON CLICKED");
remove unused logs

2023-07-24 09:25 UTC, CulturalProfessor commented
![image](https://github.com/RocketChat/Apps.Whiteboard/assets/92238941/83ade796-77d6-46e5-8dc8-63ec80128469)

2023-07-24 09:28 UTC, shiqimei commented
LGTM! @CulturalProfessor Thanks for you great work ;)

2023-07-24 09:28 UTC, merged